services:
  api:
    build:
      context: .
      dockerfile: MicroServicoPedido.API/Dockerfile               
    ports:
      - "8080:80"                         
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  
      - JWT_SECRET=2W3Jj4Gd5Lk7Rr8S6t9Zb1XqCk8Yv3F5Zc9J8Rk1Q0N=  
      - JWT_ISSUER=MicroServicoPedidoAPI    
      - JWT_AUDIENCE=MicroServicoPedidoClient 
      - JWT_EXPIRATION_IN_MINUTES=60 
    restart: always
    volumes:
      - ./data-protection-keys:/root/.aspnet/DataProtection-Keys
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  my-network:
    driver: bridge
